title: Anna
logo: assets/img/logo2.jpg
description: My portfolio
github:
  is_project_page: false
  is_user_page: true
deviantart_imgs:
- https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c18c8669-41f0-4019-9a06-e9c55ba6663c/dav8jm3-8cda172d-7e6d-44f6-b377-d99dda91420a.jpg/v1/fill/w_1032,h_774,q_70,strp/paradise_by_annie812_dav8jm3-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTIwMCIsInBhdGgiOiJcL2ZcL2MxOGM4NjY5LTQxZjAtNDAxOS05YTA2LWU5YzU1YmE2NjYzY1wvZGF2OGptMy04Y2RhMTcyZC03ZTZkLTQ0ZjYtYjM3Ny1kOTlkZGE5MTQyMGEuanBnIiwid2lkdGgiOiI8PTE2MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.l87v5j91qUMIqtTD4je1oSXVfXrVk8SH40CUzXMEQXk
deviantart_links:
  - https://www.deviantart.com/annie812/art/Paradise-657128523
  - https://www.deviantart.com/annie812/art/Gorges-de-l-Areuse-704224809
  - https://www.deviantart.com/annie812/art/Dandelion-572766707
  - https://www.deviantart.com/annie812/art/Untitled-581046648
  - https://www.deviantart.com/annie812/art/Forget-me-not-533042591
  - https://www.deviantart.com/annie812/art/Water-drops-511110637
  - https://www.deviantart.com/annie812/art/Umbrella-636443788
  - https://www.deviantart.com/annie812/art/Color-me-golden-599244904
  - https://www.deviantart.com/annie812/art/The-Secret-Garden-494848077

show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
